lesson5/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'appointments#index'
  resources :patients
  resources :physicians
  resources :appointments
  resources :diagnosis_items
end

lesson5/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

   def initialize(user)
    if user.admin_role?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

lesson5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lesson5/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

lesson5/app/models/diagnosis_item.rb
class DiagnosisItem < ApplicationRecord
  belongs_to :patient
  belongs_to :physician

  validates :content, length: { in: 1..200 }
end

lesson5/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :diagnosis_items
  has_many :physicians, through: :appointments

  validates :first_name, :last_name, length: { in: 6..20 }
  validates :email, presence: true
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 100 }
end

lesson5/app/models/physician.rb
class Physician < ApplicationRecord
  LEVEL = ['junior', 'middle', 'senior']

  has_many :appointments
  has_many :diagnosis_items
  has_many :patients, through: :appointments

  validates :first_name, :last_name, length: { in: 6..20 }
  validates :phone, presence: true, format: { with: /\A\+?380\d{9}\z/, message: 'only UA phones' }
  validates :level, presence: true, inclusion: { in: LEVEL }
end

lesson5/app/models/user.rb
class User < ApplicationRecord
  enum role: { basic: 0, admin: 1 }, _suffix: :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

lesson5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |_exception|
    flash[:alert] = "Access denided"
    redirect_to root_url
  end
end

lesson5/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource

  def create
    if @appointment.save
      redirect_to @appointment
    else
      render :new
    end
  end

  def new
    @patients = Patient.all
    @physicians = Physician.all
  end

  def edit
    @patients = Patient.all
    @physicians = Physician.all
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:patient_id, :physician_id, :appointment_date)
  end
end

lesson5/app/controllers/diagnosis_items_controller.rb
class DiagnosisItemsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.json do
        @diagnosis_items = DiagnosisItem.where(patient_id: params[:patient_id])
        render json: @diagnosis_items
      end
      format.html
    end
  end

  def create
    if @diagnosis_item.save
      redirect_to @diagnosis_item
    else
      render :new
    end
  end

  def new
    @patients = Patient.all
    @physicians = Physician.all
  end

  def edit
    @patients = Patient.all
    @physicians = Physician.all
  end

  def update
    if @diagnosis_item.update(diagnosis_item_params)
      redirect_to @diagnosis_item
    else
      render :edit
    end
  end

  def destroy
    @diagnosis_item.destroy
    redirect_to diagnosis_items_path
  end

  private

  def diagnosis_item_params
    params.require(:diagnosis_item).permit(:patient_id, :physician_id, :content)
  end
end

lesson5/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  load_and_authorize_resource

  def create
    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :email)
  end
end

lesson5/app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  load_and_authorize_resource

  def create
    if @physician.save
      redirect_to @physician
    else
      render :new
    end
  end

  def update
    if @physician.update(physician_params)
      redirect_to @physician
    else
      render :edit
    end
  end

  def destroy
    @physician.destroy
    redirect_to physician_path
  end

  private

  def physician_params
    params.require(:physician).permit(:first_name, :last_name, :level, :phone)
  end
end

lesson5/app/views/appointments/_card.html.erb
<div class = "card">
  <div class = "card-header">
  <h4><%= link_to "Appointment №" + appointment.id.to_s, appointment %></h4>
  </div>
  <div class = "card-body">
    <p><b>Patient: </b><%= appointment.patient.first_name %></p>
    <p><b>Physician: </b><%= appointment.physician.first_name %></p>
    <p><b>Date: </b><%= appointment.appointment_date %></p>
  </div>
</div>

lesson5/app/views/appointments/_form.html.erb
<%= simple_form_for @appointment do |form| %>
  <section>
    <%= form.association :patient, collection: @patients, label_method: :first_name, value_method: :id, label: "Patient", include_blank: false, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.association :physician, collection: @physicians, label_method: :first_name, value_method: :id, label: "Physician", include_blank: false, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :appointment_date, as: :date, class: 'w-20' %>
  </section>
  <%= form.button :submit, class: 'btn btn-success mt-3' %>
<% end %>

lesson5/app/views/appointments/edit.html.erb
<%= render "form" %>

lesson5/app/views/appointments/index.html.erb
<div class = "card-group">
  <% @appointments.each do |appointment| %>
    <%= render "card", appointment: appointment %>
  <% end %>
</div>
<% if can? :create, @appointment %>
  <%= link_to "Create new appointment", new_appointment_path(@appointment), class: 'btn btn-success mt-4' %>
<% end %>

lesson5/app/views/appointments/new.html.erb
<%= render "form" %>

lesson5/app/views/appointments/show.html.erb
<%= render "card", appointment: @appointment %>
<% if can? :update, @appointment %>
  <%= link_to "Edit", edit_appointment_path(@appointment), class: 'btn btn-warning m-1' %>
<% end %>
<% if can? :destroy, @appointment %>
  <%= link_to "Delete", appointment_path(@appointment), method: :delete, data: { confirm: "Вы хотите удалить встречу из системы?" }, class: 'btn btn-danger' %>
<% end %>

lesson5/app/views/diagnosis_items/_card.html.erb
<div class = "card">
  <div class = "card-header">
  <h4><%= link_to "Diagnosis №" + diagnosis_item.id.to_s, diagnosis_item %></h4>
  </div>
  <div class = "card-body">
    <p><b>Patient name: </b><%= diagnosis_item.patient.first_name %></p>
    <p><b>Physician name: </b><%= diagnosis_item.physician.first_name %></p>
  </div>
</div>

lesson5/app/views/diagnosis_items/_form.html.erb
<%= simple_form_for @diagnosis_item do |form| %>
  <section>
    <%= form.association :patient, collection: @patients, label_method: :first_name, value_method: :id, label: "Patient", include_blank: false, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.association :physician, collection: @physicians, label_method: :first_name, value_method: :id, label: "Physician", include_blank: false, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :content, input_html: {class: 'w-50 py-5'} %>
  </section>
  <%= form.button :submit, class: 'btn btn-success mt-3' %>
<% end %>

lesson5/app/views/diagnosis_items/edit.html.erb
<%= render "form" %>

lesson5/app/views/diagnosis_items/index.html.erb
<div class = "card-group">
  <% @diagnosis_items.each do |diagnosis_item| %>
    <%= render "card", diagnosis_item: diagnosis_item %>
  <% end %>
</div>
<% if can? :create, @diagnosis_item %>
  <%= link_to "Create new Diagnosis item", new_diagnosis_item_path(@diagnosis_item), class: 'btn btn-success mt-4' %>
<% end %>

lesson5/app/views/diagnosis_items/new.html.erb
<%= render "form" %>

lesson5/app/views/diagnosis_items/show.html.erb
<%= render "card", diagnosis_item: @diagnosis_item %>
<% if can? :update, @diagnosis_item %>
  <%= link_to "Edit", edit_diagnosis_item_path(@diagnosis_item), class: 'btn btn-warning m-1' %>
<% end %>
<% if can? :destroy, @diagnosis_item %>
  <%= link_to "Delete", diagnosis_item_path(@diagnosis_item), method: :delete, data: {confirm: "Вы хотите удалить встречу из системы?"}, class: 'btn btn-danger' %>
<% end %>

lesson5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class = "bg-light">
    <header>
    <nav class = "navbar navbar-expand navbar-dark bg-dark p-3 shadow">
      <a class = "navbar-brand" href="#">Hospital</a>
        <% if user_signed_in? %>
        <ul class = "navbar-nav">
          <li class = "nav-item active">
            <%= link_to "Patients", patients_path, class:'nav-link' %>
          </li>
          <li class = "nav-item">
            <%= link_to "Physicians", physicians_path, class:'nav-link' %>
          </li>
          <li class = "nav-item active">
            <%= link_to "Appointments", appointments_path, class:'nav-link' %>
          </li>
          <li class = "nav-item active">
            <%= link_to "Diagnosis items", diagnosis_items_path, class:'nav-link' %>
          </li>
        </ul>
        <ul class = "navbar-nav d-flex justify-content-end">
            <div class = "p-1">
            <li class = "nav-item">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            </div>
            <div class = "p-1">
            <li class = "nav-item ">
              <%= link_to current_user.name, edit_user_registration_path, class: "nav-link" %>
            </li>
            </div>
          <% else %>
            <li class = "nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class = "nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
    </nav>
  </header>
  <% if user_signed_in?%>
    Hello, <%= current_user.name%>
  <% end %>
    <div class = "container px-5 mt-5 shadow-lg py-3">
      <p class = "alert-success w-25 d-flex justify-content-center shadow"><%= notice %></p>
      <p class = "alert-success"><%= alert %></p>
      <%= yield %>
      <section>
        <%= link_to "Back", :back, class: "btn btn-dark my-3" %>
      </section>
    </div>
  </body>

</html>

lesson5/app/views/patients/_card.html.erb
<div class = "card">
  <div class = "card-header">
  <h3><%= link_to "Patient №" + patient.id.to_s, patient %></h3>
  </div>
  <div class = "card-body">
    <p><b>First name: </b><%= patient.first_name %></p>
    <p><b>Last name: </b><%= patient.last_name %></p>
  </div>
</div>

lesson5/app/views/patients/_form.html.erb
<%= simple_form_for @patient do |form| %>
  <section>
    <%= form.input :first_name, placeholder: 'Your first name', input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :last_name, placeholder: 'Your last name', input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :age, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :email, placeholder: 'example@test.com', input_html: {class: 'w-50'} %>
  </section>
  <%= form.button :submit, class: 'btn btn-success mt-3' %>
<% end %>

lesson5/app/views/patients/index.html.erb
<div class = "card-group">
  <% @patients.each do |patient| %>
    <div class = "card">
      <div class = "card-body">
        <%= render "card", patient: patient %>
      </div>
      <% if can? :read, DiagnosisItem %>
        <div class = "card-footer">
          <br>
            <button class = "btn btn-outline-primary show" id = "<%= patient.id %>" type = "button" data-bs-toggle = "collapse" data-bs-target = "#id<%= patient.id %>" aria-expanded = "false" aria-controls = "id<%= patient.id %>">
              Show diagnosis items
            </button>
            <div class = "collapse load" id = "id<%= patient.id %>">
              <div class="card card-body", id="show-items<%= patient.id %>">
              </div>
            </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% if can? :create, @patient %>
  <%= link_to "Create new patient", new_patient_path(@patient), class: 'btn btn-success mt-4' %>
<% end %>

lesson5/app/views/patients/show.html.erb
<%=render "card", patient: @patient %>
<% if can? :update, @patient %>
  <%= link_to "Edit", edit_patient_path(@patient), class: 'btn btn-warning m-1' %>
<% end %>
<% if can? :destoy, @patient%>
  <%= link_to "Delete", patient_path(@patient), method: :delete, data: {confirm: "Вы хотите удалить пациента из системы?"}, class: 'btn btn-danger' %>
<% end %>

lesson5/app/views/physicians/_card.html.erb
<div class = "card">
  <div class = "card-header">
  <h3><%= link_to "Physician №" + physician.id.to_s, physician %></h3>
  </div>
  <div class = "card-body">
    <p><b>First name: </b><%= physician.first_name %></p>
    <p><b>Last Name: </b><%= physician.last_name %></p>
  </div>
</div>

lesson5/app/views/physicians/_form.html.erb
<%= simple_form_for @physician do |form| %>
  <section>
    <%= form.input :first_name, placeholder: 'Your first name', input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :last_name, placeholder: 'Your last name', input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :level, collection: Physician::LEVEL, include_blank: false, input_html: {class: 'w-50'} %>
  </section>
  <section>
    <%= form.input :phone, placeholder: '+380XXXXXXXXX', input_html: {class: 'w-50'} %>
  </section>
  <%= form.button :submit, class: 'btn btn-success mt-3' %>
<% end %>

lesson5/app/views/physicians/index.html.erb
<div class = "card-group">
  <% @physicians.each do |physician| %>
    <%= render "card", physician: physician %>
  <% end %>
</div>
<% if can? :create, @physician %>
  <%= link_to "Create new physician", new_physician_path(@physician), class: 'btn btn-success mt-4' %>
<% end %>

lesson5/app/views/physicians/show.html.erb
<%=render "card", physician: @physician %>

<% if can? :update, @physician%>
  <%= link_to "Edit", edit_physician_path(@physician), class: "btn btn-warning m-1" %>
<% end %>
<% if can? :destroy, @physician%>
  <%= link_to "Delete", physician_path(@physician), method: :delete, data: {confirm: "Вы хотите удалить врача из системы?"}, class: 'btn btn-danger' %>
<% end %>